if("undefined"==typeof logposurlview)var logposurlview="";window._admislocalStorage=function(){if(!("localStorage"in window&&null!==window.localStorage))return!1;try{localStorage.setItem("_admstorage",""),localStorage.removeItem("_admstorage")}catch(a){return!1}return!0}();if(chkadmTrackingt)var chkadmTrackingt;if("undefined"==typeof __admPageloadid)var __admPageloadid=(new Date).getTime();
(function(){var a=!1,b=[];if(!window.AdmonDomReady||"function"!=typeof window.AdmonDomReady){var c=function(){if(!document.body)return setTimeout(c,13);for(var a=0;a<b.length;a++)b[a]();b=[]};window.AdmonDomReady=function(e){b.push(e);if("complete"==document.readyState)c();else if(!a){if(document.addEventListener){var d=function(){document.removeEventListener("DOMContentLoaded",d,!1);c()};document.addEventListener("DOMContentLoaded",d,!1);window.addEventListener("load",c,!1)}else if(document.attachEvent){var f=
function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),c())};document.attachEvent("onreadystatechange",f);window.attachEvent("onload",c);e=!1;try{e=null==window.frameElement}catch(l){}if(document.documentElement.doScroll&&e){var g=function(){if(0!=b.length){try{document.documentElement.doScroll("left")}catch(a){setTimeout(g,1);return}c()}};g()}}a=!0}}}})();
function admaddEventListener(a,b,c){"addEventListener"in a?a.addEventListener(b,c):"attachEvent"in a&&a.attachEvent("on"+b,c)}function admRemoveEventListener(a,b,c){"removeEventListener"in a?a.removeEventListener(b,c):"detachEvent "in a&&a.detachEvent("on"+b,c)}
if(void 0===ADM_AdsTracking)var ADM_AdsTracking={version:"1.0.0",paramFlash:{},getFlashMovie:function(a){return-1!=navigator.appName.indexOf("Microsoft")?document.getElementById(a):document[a]},checkBrowser:function(){var a=!1,b;b=navigator.appName;var c=navigator.userAgent+"",e,d=c.match(/(opera|chrome|safari|firefox|msie)\/?\s*(\.?\d+(\.\d+)*)/i);null==d&&-1==c.indexOf("MSIE")&&-1!=c.indexOf("Trident/")?(b=-1,null!=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/.exec(c)&&(b=RegExp.$1),d=["MSIE",b+""]):(d&&
null!=(e=c.match(/version\/([\.\d]+)/i))&&(d[2]=e[1]),d=d?[d[1],d[2]]:[b,navigator.appVersion,"-?"]);b=d;"undefined"!=typeof b&&null!=b&&1<=b.length&&(c=(b[0]+"").toLowerCase(),b=b[1].split("."),b=parseInt(b[0]),("firefox"==c&&22<=b||"msie"==c&&10<=b||"safari"==c&&5<=b||"chrome"==c)&&_admislocalStorage&&(a=!0));return a},fonts:"",getFont:function(a){ADM_AdsTracking.fonts=a},lcStorage:{timestamp:"timestamp_",get_exprises:function(a,b,c,e){a+="";b=a.indexOf(b,c);c=a.length-1;return-1!=b?(e=a.indexOf(e,
b),-1==e&&(e=c),a.substring(b,e)):""},set_item:function(a,b,c){var e,d=(new Date).getTime(),f=this.timestamp,d=0==c||""==c?d+63072E7:d+864E5*c;e="_azs"==a?";":",";c=this.get_exprises(b,f,0,e);b=""==c?b+(f+d.toString()+e):b.replace(c,f+d.toString());localStorage.setItem(a,b)},get_item:function(a,b){var c=localStorage.getItem(a),e=(new Date).getTime(),d=this.timestamp;if(""==c||null==c)return"";endchar="_azs"==a?";":",";var f=this.get_exprises(c,d,0,endchar),f=f.replace(d,"");return""==f||isNaN(parseInt(f))||
parseInt(f)<e?"":c.replace(d+f+endchar,"")},remove_item:function(a){localStorage.removeItem(a)},flush:function(){localStorage.clear()}},setCookie:function(a,b,c,e,d,f){(new Date).getTime();e="/";c=0==c||""==c?(new Date(+new Date+63072E7)).toGMTString():(new Date(+new Date+864E5*c)).toGMTString();a=[a+"="+escape(b)];for(var g in c={expires:c,path:e,domain:d})c[g]&&a.push(g+"="+c[g]);return f&&a.push("secure"),document.cookie=a.join(";"),!0},getCookie:function(a){return 0<document.cookie.length&&(c_start=
document.cookie.indexOf(a+"="),-1!=c_start)?(c_start=c_start+a.length+1,c_end=document.cookie.indexOf(";",c_start),-1==c_end&&(c_end=document.cookie.length),unescape(document.cookie.substring(c_start,c_end))):""},get:function(a){var b="",c="";if("__ui"==a||"__uid"==a||"__create"==a)c=a,a="__uif";if(_admislocalStorage){if("__R"==a||"__RC"==a||"__uif"==a)b=ADM_AdsTracking.getCookie(a);if(null==b||""==b)b=ADM_AdsTracking.lcStorage.get_item(a),null!=b&&""!=b&&ADM_AdsTracking.setCookie(a,b,"")}else b=
ADM_AdsTracking.getCookie(a);if(""!=c&&""!=b){a=b.split("|");for(var e=0,d=a.length;e<d;e++)if(-1!=a[e].indexOf(c+":")){b=a[e].replace(c+":","");break}}return b},set:function(a,b,c){if(_admislocalStorage){if(ADM_AdsTracking.lcStorage.set_item(a,b,c),"__R"==a||"__RC"==a||"__uif"==a)"__R"==a&&"undefined"!=typeof ADS_Location&&ADS_Location!=b&&""!=b&&"0"!=b&&(ADS_Location=parseInt(b)),"__RC"==a&&"undefined"!=typeof ADS_City&&ADS_City!=b&&""!=b&&"0"!=b&&(ADS_City=parseInt(b)),ADM_AdsTracking.setCookie(a,
b,c)}else ADM_AdsTracking.setCookie(a,b,c)},getParam:function(){if(ADM_AdsTracking.checkBrowser()){var a=ADM_AdsTracking.get("__create")+"",b=ADM_AdsTracking.get("__uid")+"";30<b.length&&(b="");""==b&&(a="");11<a.length&&""!=b&&(a=Math.floor((new Date).getTime()/1E3));return"&ce=1&lc="+ADM_AdsTracking.get("__RC")+"&cr="+a+"&ui="+b}return""},getInfoParam:function(){if(ADM_AdsTracking.checkBrowser())return"";var a=ADM_AdsTracking.get("__uid"),b=ADM_AdsTracking.get("__create");return"&ce=1&guie=1&__uid="+
a+"&__create="+b},flashcheck:function(a){for(var b in a)ADM_AdsTracking.check(b,a[b],!0)},expireAllCookies:function(a,b){var c=(new Date(0)).toUTCString();document.cookie=a+"=; expires="+c;for(var e=0,d=b.length;e<d;e++)document.cookie=a+"=; path="+b[e]+"; expires="+c},expireActiveCookies:function(a){for(var b=location.pathname.replace(/\/$/,"").split("/"),c=[],e=0,d=b.length,f;e<d;e++)f=b.slice(0,e+1).join("/"),f=f.replace(/\.([\w]+)/gi,""),""!=f&&(c.push(f),c.push(f+"/"));0<c.length&&ADM_AdsTracking.expireAllCookies(a,
c)},check:function(a,b){switch(a){case "__ui":case "__uid":case "__create":if(2==arguments.length&&"__uid"==a||"__create"==a&&""!=b){ADM_AdsTracking.paramFlash[a]=b;var c=ADM_AdsTracking.getFlashMovie("_admFlck");c&&c.setck&&c.setck(ADM_AdsTracking.paramFlash)}var e=ADM_AdsTracking.get("__uif")+"";if(""==e)e=a+":"+b;else{for(var c=a+":"+b,e=e.split("|"),d=[],f=0,g=e.length;f<g;f++)-1==e[f].indexOf(a+":")&&d.push(e[f]);d.push(c);e=d.join("|")}ADM_AdsTracking.set("__uif",e,10);break;default:e=ADM_AdsTracking.get(a),
2==arguments.length&&""!=b&&"0"!=b&&"-1"!=b&&(ADM_AdsTracking.paramFlash[a]=b,(c=ADM_AdsTracking.getFlashMovie("_admFlck"))&&c.setck&&c.setck(ADM_AdsTracking.paramFlash)),e!=b&&ADM_AdsTracking.set(a,b,"")}}};if("undefined"==typeof admaddEventListener)var admaddEventListener$1=function(a,b,c){"addEventListener"in a?a.addEventListener(b,c):"attachEvent"in a&&a.attachEvent("on"+b,c)};
if("undefined"==typeof wPrototype)var wPrototype={wdHeight:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerHeight:b.documentElement&&b.documentElement.clientHeight?a=b.documentElement.clientHeight:b.body&&b.body.clientHeight&&(a=b.body.clientHeight);return a},wdWidth:function(){var a,b=document;"number"==typeof window.innerWidth?a=window.innerWidth:b.documentElement&&b.documentElement.clientWidth?a=b.documentElement.clientWidth:b.body&&b.body.clientWidth&&(a=b.body.clientWidth);
return a},getElementTop:function(a){var b=document;if(b.getElementById)var c=b.getElementById(a);else b.all&&(c=b.all[a]);if(null!=c){yPos=c.offsetTop;for(tempEl=c.offsetParent;null!=tempEl;)yPos+=tempEl.offsetTop,tempEl=tempEl.offsetParent;return yPos}return 150},getElementWidth:function(a){return document.getElementById(a).clientWidth},getElementLeft:function(a){var b,c=document;c.getElementById?b=c.getElementById(a):c.all&&(b=c.all[a]);a=b.offsetLeft;for(b=b.offsetParent;null!=b;)a+=b.offsetLeft,
b=b.offsetParent;return a},scrollTop:function(){var a=document,b=a.body.scrollTop;0==b&&(b=window.pageYOffset?window.pageYOffset:a.body.parentElement?a.body.parentElement.scrollTop:0);return b},scrollLeft:function(){var a=document,b=window.pageXOffset?window.pageXOffset:0,c=a.documentElement?a.documentElement.scrollLeft:0,a=a.body?a.body.scrollLeft:0,b=b?b:0;c&&(!b||b>c)&&(b=c);return a&&(!b||b>a)?a:b},bdWidth:function(){var a=document;return bodyWidth=Math.max(Math.max(a.body.scrollWidth,a.documentElement.scrollWidth),
Math.max(a.body.offsetWidth,a.documentElement.offsetWidth),Math.max(a.body.clientWidth,a.documentElement.clientWidth))},bdHeight:function(){var a=document;return Math.max(Math.max(a.body.scrollHeight,a.documentElement.scrollHeight),Math.max(a.body.offsetHeight,a.documentElement.offsetHeight),Math.max(a.body.clientHeight,a.documentElement.clientHeight))}};
var _ADMFlashDetect=new function(){var a=this;a.installed=!1;a.raw="";a.major=-1;a.minor=-1;a.revision=-1;a.revisionStr="";var b=[{name:"ShockwaveFlash.ShockwaveFlash.7",version:function(a){return c(a)}},{name:"ShockwaveFlash.ShockwaveFlash.6",version:function(a){var b="6.0.r21";try{a.AllowScriptAccess="always",b=c(a)}catch(f){}return b}},{name:"ShockwaveFlash.ShockwaveFlash",version:function(a){return c(a)}}],c=function(a){var b=-1;try{b=a.GetVariable("$version")}catch(c){}return b};a.majorAtLeast=
function(b){return a.major>=b};a.minorAtLeast=function(b){return a.minor>=b};a.revisionAtLeast=function(b){return a.revision>=b};a.versionAtLeast=function(b){var c=[a.major,a.minor,a.revision],f=Math.min(c.length,arguments.length);for(i=0;i<f;i++)if(c[i]>=arguments[i]){if(!(i+1<f&&c[i]==arguments[i]))return!0}else return!1};a._ADMFlashDetect=function(){var c,d,f,g,l;if(navigator.plugins&&0<navigator.plugins.length){var h=navigator.mimeTypes;if(h&&h["application/x-shockwave-flash"]&&h["application/x-shockwave-flash"].enabledPlugin&&
h["application/x-shockwave-flash"].enabledPlugin.description){c=h=h["application/x-shockwave-flash"].enabledPlugin.description;var h=c.split(/ +/),k=h[2].split(/\./),h=h[3];d=parseInt(k[0],10);f=parseInt(k[1],10);g=h;l=parseInt(h.replace(/[a-zA-Z]/g,""),10)||a.revision;a.raw=c;a.major=d;a.minor=f;a.revisionStr=g;a.revision=l;a.installed=!0}}else if(-1==navigator.appVersion.indexOf("Mac")&&window.execScript)for(h=-1,k=0;k<b.length&&-1==h;k++){c=-1;try{c=new ActiveXObject(b[k].name)}catch(m){c={activeXError:!0}}c.activeXError||
(a.installed=!0,h=b[k].version(c),-1!=h&&(c=h,g=c.split(","),d=parseInt(g[0].split(" ")[1],10),f=parseInt(g[1],10),l=parseInt(g[2],10),g=g[2],a.raw=c.replace("Shockwave Flash ",""),a.major=d,a.minor=f,a.revision=l,a.revisionStr=g))}}()},paramBrowser={screen_Resolution:screen.width+"x"+screen.height,screen_Color:screen.colorDepth,hostname:document.domain.replace("www.",""),cookieEnabled:navigator.cookieEnabled?1:0,javaEnabled:navigator.javaEnabled()?1:0,referrer:document.referrer,url:function(){var a=
window.location!=window.parent.location?document.referrer:document.location+"",b=this.hostname;return""==b?a:a.substring(a.indexOf(b)+b.length,a.length)},flashVersion:function(){return _ADMFlashDetect.major+"."+_ADMFlashDetect.minor+"."+_ADMFlashDetect.revisionStr},zenURL:{encode:function(a){if(-1!=document.domain.indexOf("muachung.vn")&&-1==a.indexOf("http://")){for(var b="undefined"==typeof ADS_CHECKER?"":ADS_CHECKER.getCookie("mc_city"),c="/ha-noi /tp-ho-chi-minh /da-nang /nha-trang /vung-tau /hai-phong".split(" "),
e="/Ha-Noi /TP-HCM /Da-Nang /Khanh-Hoa /Ba-Ria-Vung-Tau /Hai-Phong".split(" "),d=0;d<c.length;d++)if(0==a.indexOf(c[d]))return a=a.replace(c[d],e[d]),encodeURIComponent(a);c={22:"/Ha-Noi",29:"/TP-HCM",15:"/Da-Nang",68:"/Khanh-Hoa",26:"/Hai-Phong",67:"/Ba-Ria-Vung-Tau"};""!=b&&"undefined"!=typeof c[b]&&(a=c[b]+a)}return encodeURIComponent(a)},decode:function(a){return decodeURIComponent(a.replace(/\+/g," "))}}},_ADMBrowser={Version:function(){var a=999;try{var b=navigator.userAgent+"";-1!=navigator.appVersion.indexOf("MSIE")&&
(a=parseFloat(navigator.appVersion.split("MSIE")[1]));if(-1!=b.indexOf("Trident")){var c=/Trident\/.*rv:([0-9]{1,}[.0-9]{0,})/.exec(b);c&&2<=c.length&&(a=parseFloat(c[1]))}}catch(e){}return a}},_admBrV=_ADMBrowser.Version();
function ADM_TrackingSendChk(){__ADMisActive=__ADMwdVis()?1:0;var a=Math.floor((new Date).getTime()/1E3);if(1==__ADMisActive||120<=a-__ADMTimeTk)__ADMTimeTk=a,(new Image).src=window.__ADMTrackingSendUrl+logposurlview+"&i="+encodeURIComponent("p;"+__admPageloadid+";"+__ADMScrollcounter+";"+__ADMScrollEnd+";"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+";"+__admloadPageId+";"+__admloadPageIdc)+
ADM_AdsTracking.getParam();chkadmTrackingt=999>_admBrV?window.setTimeout("ADM_TrackingSendChk()",2E4):window.setTimeout("ADM_TrackingSendChk()",6E4)}var __ADMwdVis=function(){var a,b,c={hidden:"visibilitychange",webkitHidden:"webkitvisibilitychange",mozHidden:"mozvisibilitychange",msHidden:"msvisibilitychange"};for(a in c)if(a in document){b=c[a];break}return function(c){c&&document.addEventListener(b,c);return!document[a]}}();
function ADM_TrackingSend(){if("undefined"!=typeof __ADM_TrackingSend&&!0===__ADM_TrackingSend)return!1;var a=ADM_AdsTracking.checkBrowser(),b="",c=0,b="//lg1.logging.admicro.vn/_tracking1.gif?dg="+__admloadPageIdc,b=b+("&fl="+paramBrowser.flashVersion()),b=b+("&je="+paramBrowser.javaEnabled),b=b+("&sr="+paramBrowser.screen_Resolution),b=b+("&sc="+paramBrowser.screen_Color),b=b+("&hn="+paramBrowser.hostname),b=b+("&p="+paramBrowser.zenURL.encode(paramBrowser.url())),b=b+("&r="+(""==paramBrowser.referrer?
paramBrowser.referrer:paramBrowser.zenURL.encode(paramBrowser.referrer))),b="undefined"!=typeof _Analytics_Channel&&""!=_Analytics_Channel?b+("&cat="+encodeURIComponent(decodeURIComponent(_Analytics_Channel))):"undefined"!=typeof _ADM_Channel&&""!=_ADM_Channel?b+("&cat="+encodeURIComponent(decodeURIComponent(_ADM_Channel))):b+"&cat=",e;try{e=window.self!==window.top}catch(f){e=!0}e=e?1:0;"undefined"!=typeof ADS_CHECKER&&(-1!=paramBrowser.hostname.indexOf("enbac.com")&&(c=""!=ADS_CHECKER.getCookie("province_id")?
ADS_CHECKER.getCookie("province_id"):0),-1!=paramBrowser.hostname.indexOf("rongbay.com")&&(c=""!=ADS_CHECKER.getCookie("cityid")?ADS_CHECKER.getCookie("cityid"):0),-1!=paramBrowser.hostname.indexOf("muachung.vn")&&(c=""!=ADS_CHECKER.getCookie("muachung_cityMC")?ADS_CHECKER.getCookie("muachung_cityMC"):0));b+="&g="+c;window.__ifr=e;window.__ADM_TrackingSend=!0;window.__ADMScrollcounter=0;window.__ADMScrollEnd=0;window.__ADMTrackingSendUrl=b;window.__ADMTouch=0;window.__ADMMouse=0;window.__ADMisActive=
0;window.__ADMTimeTk=Math.floor((new Date).getTime()/1E3);try{__ADMwdVis()&&(window.__ADMisActive=1)}catch(f){}b+="&i="+encodeURIComponent("s;"+__admPageloadid+";0;0;"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+";"+__admloadPageId+";"+__admloadPageIdc)+"&rdm="+Math.random();(new Image).src=window.__ADMTrackingSendUrl+logposurlview+"&i="+encodeURIComponent("v;"+__admPageloadid+";"+window.__ADMScrollcounter+
";"+window.__ADMScrollEnd+";"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+";"+__admloadPageId+";"+__admloadPageIdc)+"&rdm="+Math.random()+ADM_AdsTracking.getParam();-1!=(navigator.userAgent+"").indexOf("Firefox")&&(a=!1);if(!0===a){var d=document.createElement("iframe");d.src=b+ADM_AdsTracking.getParam();d.style.width="12px";d.style.height="12px";d.style.visibility="hidden";d.style.position=
"absolute";d.style.left="0px";d.style.bottom="0px";d.style.border="none";d.target="admTrackmain";d.name="admIframeTracking";d.id="admIframeTracking";a=document.domain+"";-1!=a.indexOf("soha.vn")||-1!=a.indexOf("dantri.com.vn")||-1!=a.indexOf("genk.vn")||-1!=a.indexOf("gamek.vn")?AdmonDomReady(function(){document.body.appendChild(d)}):document.body.appendChild(d);a=function(a){if(-1!=a.origin.indexOf("logging.admicro.vn")&&(a=a.data,"object"==typeof a))try{"__CRT"==a[0]&&(a[0]="__create"),"__UF"==
a[0]&&(a[0]="__ui"),"__C"!=a[0]&&ADM_AdsTracking.check(a[0],a[1],"","/")}catch(b){}};window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent("onmessage",a,!1)}else d=document.createElement("script"),d.type="text/javascript",d.async=!0,d.src=b,a=document.getElementsByTagName("script")[0],a.parentNode.insertBefore(d,a);admaddEventListener(window,"scroll",function(){window.__ADMScrollcounter+=1;0>wPrototype.bdHeight()-(wPrototype.scrollTop()+wPrototype.wdHeight()+100)&&(window.__ADMScrollEnd=
1)});admaddEventListener(window,"blur",function(){__ADMisActive=0});admaddEventListener(window,"focus",function(){__ADMisActive=1});"ontouchstart"in window&&admaddEventListener(document,"touchmove",function(a){__ADMTouch++});admaddEventListener(document,"mousemove",function(a){__ADMMouse++});window.setTimeout(function(){var a,b,c="",d={hidden:"visibilitychange",webkitHidden:"webkitvisibilitychange",mozHidden:"mozvisibilitychange",msHidden:"msvisibilitychange"};for(a in d)if(a in document){b=d[a];
c=a;break}document.addEventListener(b,function(){__ADMisActive=document[c]?0:1;(new Image).src=window.__ADMTrackingSendUrl+logposurlview+"&i="+encodeURIComponent("p;"+__admPageloadid+";"+__ADMScrollcounter+";"+__ADMScrollEnd+";"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+";"+__admloadPageId+";"+__admloadPageIdc)+"&rdm="+Math.random()+ADM_AdsTracking.getParam()})},5E3);chkadmTrackingt=window.setTimeout(function(){ADM_TrackingSendChk()},
2E4);if("beforeunload"in window||"onbeforeunload"in window)-1!=navigator.userAgent.indexOf("Firefox")?admaddEventListener(window,"unload",function(){(new Image).src=window.__ADMTrackingSendUrl+logposurlview+"&i="+encodeURIComponent("e;"+__admPageloadid+";"+window.__ADMScrollcounter+";"+window.__ADMScrollEnd+";"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+";"+__admloadPageId+";"+__admloadPageIdc)+
"&rdm="+Math.random()+ADM_AdsTracking.getParam()}):admaddEventListener(window,"beforeunload",function(){(new Image).src=window.__ADMTrackingSendUrl+logposurlview+"&i="+encodeURIComponent("e;"+__admPageloadid+";"+window.__ADMScrollcounter+";"+window.__ADMScrollEnd+";"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+";"+__admloadPageId+";"+__admloadPageIdc)+"&rdm="+Math.random()+ADM_AdsTracking.getParam()})}
if("undefined"==typeof __admloadPageId){var __admloadPageId=function(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return a()+a()+a()+a()+a()+a()+a()+a()}();if(_admislocalStorage){var __admloadPageIdc=localStorage.__uidac;__admloadPageIdc||(__admloadPageIdc=localStorage.__uidac=__admloadPageId)}else __admloadPageIdc=ADM_AdsTracking.getCookie("__uidac"),""==__admloadPageIdc&&ADM_AdsTracking.setCookie("__uidac",__admloadPageId,2E3,"")}ADM_TrackingSend();
function _admloadJs1(a,b){var c=document.createElement("script");c.type="text/javascript";c.src=a;2<=arguments.length&&(c.onload=b,c.onreadystatechange=function(){4!=c.readyState&&"complete"!=c.readyState||b()});document.getElementsByTagName("head")[0].appendChild(c)};

var logposurlview="";!function(){function m(){c!=-1&&clearTimeout(c),c=window.setTimeout(function(){n()},100)}function n(){if(he=document.body.scrollTop+b,he>a){a=he;for(var c=0;c<d;c++)if(a>f[c]){var e=g[c],k=f[c],l=e+":"+k;l=encodeURIComponent(l),j.push(l),i.push(c),f.splice(0,1),g.splice(0,1),logposurlview="&sl="+a+"&si="+j,img=new Image,img.src=window.__ADMTrackingSendUrl+logposurlview+"&i="+encodeURIComponent("p;"+__admPageloadid+";"+window.__ADMScrollcounter+";"+window.__ADMScrollEnd+";"+__ADMisActive+";"+__ADMMouse+";"+__ADMTouch+";"+(wPrototype.wdWidth()+"x"+wPrototype.wdHeight())+";"+window.__ifr+";"+("undefined"==typeof ADS_CHECKER?0:1)+";"+__admloadPageId+";"+__admloadPageIdc)+"&rdm="+Math.random()+ADM_AdsTracking.getParam(),h&&clearTimeout(h),h=window.setTimeout(function(){ADM_TrackingSendChk()},2e4)}logposurlview="&sl="+a+"&si="+j}}if("soha.vn"!=window.location.hostname&&"kenh14.vn"!=window.location.hostname)return!0;var a=0,b=window.innerHeight,c=-1,d=0,e=[];e=document.querySelectorAll("[data-check-position]"),d=e.length;for(var h,f=[],g=[],i=[],j=[],k=0;k<d;k++){f.push(e[k].offsetTop);var l=e[k].getAttributeNode("data-check-position").value;g.push(l)}window.addEventListener("scroll",m)}();