var q=!0,s=!1;
(function(){function n(){this.b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="}function r(){this.s()}Array.prototype.indexOf||(Array.prototype.indexOf=function(b,a){var d=this.length>>>0,c=Number(a)||0,c=0>c?Math.ceil(c):Math.floor(c);for(0>c&&(c+=d);c<d;c++)if(c in this&&this[c]===b)return c;return-1});(function(){if(typeof window.SC_ContainerElement!="function"){var b=function(a,b){var c;c||(c=document);var e=c.getElementById(b+a)||c.getElementById(b+"_"+a);if(e)return e;c=
c.getElementsByTagName("ins");for(e=0;e<c.length;e++)if(c[e].getAttribute("class")=="SC_TBlock"&&c[e].getAttribute("data-ad-block")==a&&!c[e].getAttribute("data-ad-built"))return c[e]};window.SC_ContainerElement=function(a,d,c){d||(d="SC_TBlock");var e=b(a,d);e&&c&&SC_ContainerMarkBuilt(a,d);if(!e)throw Error("No one div for ["+a+"]");return e};window.SC_ContainerMarkBuilt=function(a,d){var c=b(a,d);c&&c.setAttribute("data-ad-built","1")}}}).call();var v={get:function(b,a){typeof a==="undefined"&&
(a=null);var d=document.cookie,c=b+"=",e=d.indexOf("; "+c);if(e==-1){e=d.indexOf(c);if(e!==0)return a}else e=e+2;var f=document.cookie.indexOf(";",e);if(f==-1)f=d.length;return decodeURIComponent(d.substring(e+c.length,f))},set:function(b,a,d,c){var e=new Date,c=c||"domain",f="/";if(a){d=e.getTime()+d*6E4;c=="session"&&(d=0)}else d=e.getTime()-1;d&&(d=(new Date(d)).toGMTString());c=="page"&&(f="");b=b+"="+encodeURIComponent(a);f&&(b=b+("; path="+f));d&&(b=b+("; expires="+d));document.cookie=b}},g=
{H:43200,D:function(b){function a(){try{k.doScroll("left")}catch(b){setTimeout(a,50);return}d("poll")}function d(a){if(!(a.type=="readystatechange"&&h.readyState!="complete")){(a.type=="load"?f:h)[n](l+a.type,d,s);if(!c&&(c=q))b.call(f,a.type||a)}}var c=s,e=q,f=window,h=f.document,k=h.documentElement,m=h.addEventListener,g=m?"addEventListener":"attachEvent",n=m?"removeEventListener":"detachEvent",l=m?"":"on";if(h.readyState=="complete")b.call(f,"lazy");else{if(!m&&k.doScroll){try{e=!f.frameElement}catch(j){}e&&
a()}h[g](l+"DOMContentLoaded",d,s);h[g](l+"readystatechange",d,s);f[g](l+"load",d,s)}},log:function(b){window._sc_dbg&&console.log(b)},N:function(){return{w:document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth,h:document.documentElement.clientHeight||window.innerHeight||document.body.clientHeight}},l:function(b){var a=document.getElementById(b);g.log("sizeInfo->blockSize["+b+"]: "+a.offsetWidth+"x"+a.offsetHeight);return{w:a.offsetWidth,h:a.offsetHeight}},g:function(b){var a=
g.N();return"sz_"+b+"_"+(window.outerWidth||a.w)},F:function(b){var a=v.get(g.g(b));g.log("sizeInfo->get by ["+g.g(b)+"] => "+a);if(!a)return a;try{a=JSON.parse(a)}catch(d){return null}return a},G:function(b,a){g.D(function(){function d(a){g.log("sizeInfo->set ["+g.g(b)+"] => "+JSON.stringify(a));v.set(g.g(b),JSON.stringify(a),g.H)}var c=g.l(a);if(c.w&&c.h)return d(c);var e=10,f=setInterval(function(){var b=g.l(a);b.w&&b.h&&d(b);--e===0&&clearInterval(f)},500)})},Q:function(b,a){g.G(b,a)}},x=["UNKNOWN",
"ETHERNET","WIFI","CELL_2G","CELL_3G"];r.prototype.s=function(){this.win={w:0,h:0};if(document&&document.documentElement){if(document.documentElement.clientWidth)this.win.w=document.documentElement.clientWidth;if(document.documentElement.clientHeight)this.win.h=document.documentElement.clientHeight}this.screen={width:screen.width||-1,height:screen.height||-1,colorDepth:screen.colorDepth||0,pixelDepth:screen.pixelDepth||0};var b=this.u();this.navigator={language:navigator.language||"",browserLanguage:navigator.browserLanguage||
"",systemLanguage:navigator.systemLanguage||"",userLanguage:navigator.userLanguage||"",platform:navigator.platform||"",vendor:navigator.vendor||"",timeZone:(new Date).getTimezoneOffset()*-1/60,date:new Date,hour:(new Date).getHours(),width:b.width||-1,height:b.height||-1,plugins:this.t(),flashVersion:this.r()};this.navigator.connectionType="undef";typeof navigator.P!=="undefined"&&x[navigator.connection.type]&&(this.navigator.connectionType=x[navigator.connection.type])};r.prototype.d=function(b){function a(){return""}
var d=new n;if(typeof JSON!=="undefined")if(typeof JSON.stringify!=="undefined")a=JSON.stringify;else if(typeof JSON.i!=="undefined")a=JSON.i;return d.i(a(b))};r.prototype.q=function(){return this.d(this)};r.prototype.t=function(){var b=[],a;for(i=0;i<navigator.plugins.length;i++){a=navigator.plugins[i].name.replace(/[^A-Za-z 0-9 \.,\?""!@#\$%\^&\*\(\)-_=\+;:<>\/\\\|\}\{\[\]`~]*/g,"").trim();a!==""&&b.push(a)}var d,c;for(d=b.length;d;)for(a=--d;a>0;)if(b[d]===b[--a]){for(c=a;--a&&b[d]===b[a];);d=
d-b.splice(a+1,c-a).length}return b};r.prototype.u=function(){var b={};if(typeof window.innerWidth!="undefined"){b.width=window.innerWidth;b.height=window.innerHeight}else if(typeof document.documentElement!=="undefined"&&typeof document.documentElement.clientWidth!=="undefined"&&document.documentElement.clientWidth!==0){b.width=document.documentElement.clientWidth;b.height=document.documentElement.clientHeight}else{b.width=document.getElementsByTagName("body")[0].clientWidth;b.height=document.getElementsByTagName("body")[0].clientHeight}return b};
r.prototype.r=function(){try{try{var b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{b.O="always"}catch(a){return"6.0.0"}}catch(d){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(c){try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,".").match(/^\.?(.+)\.?$/)[1]}catch(e){}}return s};
n.prototype.I=function(b){for(var a="",d,c,e,f,h,k=0,b=b.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<b.length;){d=this.b.indexOf(b.charAt(k++));c=this.b.indexOf(b.charAt(k++));f=this.b.indexOf(b.charAt(k++));h=this.b.indexOf(b.charAt(k++));d=d<<2|c>>4;c=(c&15)<<4|f>>2;e=(f&3)<<6|h;a=a+String.fromCharCode(d);f!=64&&(a=a+String.fromCharCode(c));h!=64&&(a=a+String.fromCharCode(e))}return a=this.z(a)};n.prototype.A=function(b){for(var b=b.replace(/\r\n/g,"\n"),a="",d=0;d<b.length;d++){var c=b.charCodeAt(d);if(c<
128)a=a+String.fromCharCode(c);else{if(c>127&&c<2048)a=a+String.fromCharCode(c>>6|192);else{a=a+String.fromCharCode(c>>12|224);a=a+String.fromCharCode(c>>6&63|128)}a=a+String.fromCharCode(c&63|128)}}return a};n.prototype.z=function(b){for(var a="",d=0,c=0,e=0;d<b.length;){c=b.charCodeAt(d);if(c<128){a=a+String.fromCharCode(c);d++}else if(c>191&&c<224){e=b.charCodeAt(d+1);a=a+String.fromCharCode((c&31)<<6|e&63);d=d+2}else{e=b.charCodeAt(d+1);c3=b.charCodeAt(d+2);a=a+String.fromCharCode((c&15)<<12|
(e&63)<<6|c3&63);d=d+3}}return a};n.prototype.i=function(b){for(var a="",d,c,e,f,h,k,m=0,b=this.A(b);m<b.length;){d=b.charCodeAt(m++);c=b.charCodeAt(m++);e=b.charCodeAt(m++);f=d>>2;d=(d&3)<<4|c>>4;h=(c&15)<<2|e>>6;k=e&63;isNaN(c)?h=k=64:isNaN(e)&&(k=64);a=a+this.b.charAt(f)+this.b.charAt(d)+this.b.charAt(h)+this.b.charAt(k)}return a};n.prototype.n=function(b){this.i(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")};(function(){function b(a){this.m(a)}function a(a){for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c)+
c);return String.fromCharCode.apply(String,b)}function d(){for(var a=[],b=document.getElementsByTagName("head")[0].getElementsByTagName("meta"),c=0;c<b.length;c++)b[c].name.toLowerCase()=="description"&&a.push(b[c].content);return a.join(",")}b.prototype={m:function(a){a||(a={});this.a=a;this.a.block_settings||(this.a.block_settings={});this.id=a.id;var b;if(!(b=a.domain)){b=[];for(var c=0;c<15;c++)b.push("ae0vqfisqlu9o|{".charCodeAt(c)-c);b=String.fromCharCode.apply(String,b)}this.domain=b;this.L();
this.e=new r;this.c=a.settings;try{var d=(new n).I(this.c);this.c=JSON.parse(d)}catch(e){this.c={}}this.j=this.c.prefixName||this.c.prefix||a.prefix;this.c.prefix=this.j},L:function(){var a=document.createElement("script");a.type="text/javascript";a.src="//sync.users-api.com/etg.js";a.onerror=function(){window.__sc_int_uid="ssp-etg-error"};document.getElementsByTagName("head")[0].appendChild(a)},p:function(){this.M()},o:function(b,c){var e,m=[];e=document.referrer;try{window.opener&&window.opener.document&&
(e=window.opener.document.location.toString())}catch(r){}var u=navigator.cookieEnabled||"cookie"in document&&(document.cookie.length>0||(document.cookie="test").indexOf.call(document.cookie,"test")>-1),l={},j,p=["SC_rich","SC_catfish"],t;for(t in p)if(p.hasOwnProperty(t))(j=this.k(t,""))&&(l[t]=j);(j=g.F(this.id))&&(j=j.w+"x"+j.h);p=this.e.d(this.c);t=window.__sc_int_uid||window.__sc_uid||this.k("uuid1","");e={Id:b.join("_"),uid:t,sync:window.__sc_uid_synced||"0",hours:(new Date).getHours(),ajax:c?
"1":"0",domain:this.domain,cld:this.a.click_domain||"",clt:this.a.click_track_url||"",unq:this.unique,sub_id:this.a.subid,cookies:u?"1":"0",_c:this.e.d(l),redir:this.a.redir,RNum:Math.floor(Math.random()*1E4),Referer_:(new n).n(a(e.substring(0,512))),docurl_:(new n).n(a(document.location.href)),client_info:this.e.q(),doc_inf:this.e.d({title:encodeURIComponent(document.title),description:encodeURIComponent(d()),charSet:document.characterSet}),set:p,ver:"8",add_params:this.a.add_params,bls:j};e.doc_inf.length>
1024&&delete e.doc_inf;u="";j=this.a._sc_params||{};var p=this.a._sc_debug||{},l={},o;j||(j={});p||(p={});for(o in j)j.hasOwnProperty(o)&&(l[o]=j[o]);for(o in p)p.hasOwnProperty(o)&&(l[o]=p[o]);o=0;for(var v in l)o++;o===0||(u=u+("&_sc_debug="+this.e.d(l)));for(var w in e)e.hasOwnProperty(w)&&e[w]&&m.push(encodeURIComponent(w)+"="+encodeURIComponent(e[w]));return m.join("&")+u},J:function(a){var b=SC_ContainerElement(this.id,this.j);b.innerHTML="";var c=document.createElement("iframe");b.appendChild(c);
c.style.cssText="width:100%;";var a={frameborder:"0",marginheight:"0",marginwidth:"0",scrolling:"no",id:"SC_TBlock_"+this.id+"_frame",src:a+"&iframe=1"},d;for(d in a)a.hasOwnProperty(d)&&c.setAttribute(d,a[d]);window.addEventListener("message",function(a){if(a.data.type=="frameHeightSet")c.style.height=a.data.height},s)},v:function(){for(var a,b=0;b<this.f.length;b++){a=this.f[b];var c="//"+this.domain+"/a?"+this.o([a]);if(this.a.iframe)this.J(c);else{if(a=SC_ContainerElement(a,this.j))a.innerHTML=
"";a=document.createElement("script");a.type="text/javascript";a.src=c;document.getElementsByTagName("body")[0].appendChild(a)}}},C:function(){var a=this;if(!a.id||a.id=="undefined")console.log("Error: Need block id(s).");else{var b=String(a.id).split(/_/);this.f=[];for(var c in b)b.hasOwnProperty(c)&&this.f.push(b[c]);if(this.f.length===0)throw Error("No one div for ["+a.id+"]");a.p(this.f);var d=50,e=setInterval(function(){--d===0&&window.__sc_int_uid&&(window.__sc_int_uid="ssp-etg-timeout-100");
if(window.__sc_int_uid){clearInterval(e);a.v()}},20)}},B:function(a,b){var c=a;if(typeof a==="object"){this.m(a);c=a.id}this.p([c]);var c="//"+this.domain+"/a?"+this.o([c],q),d;if(typeof XMLHttpRequest!="undefined")d=new XMLHttpRequest;else try{d=new ActiveXObject("Msxml2.XMLHTTP")}catch(e){try{d=new ActiveXObject("Microsoft.XMLHTTP")}catch(g){d=0}}if(d){d.onreadystatechange=function(){if(d.readyState==4){if(d.status==200){var a=d.responseText,a=JSON.parse(a);return b(null,a)}return b(Error("Response status: "+
d.status))}};d.open("GET",c,q);d.send(null)}else b(Error("no ajax object"))},K:function(){var a=q;typeof this.a.site_cookies!="undefined"&&(a=this.a.site_cookies);if(a)return[106323,101008].indexOf(parseInt(this.id,10))!==-1?s:q},M:function(){if(this.K()){var a="SC_unique_"+this.id,b=1;this.k(a,0)&&(b=0);this.unique=b;var c="."+document.domain.split("www.").join(""),d=new Date;d.setDate(d.getDate()+1);d.setHours(0,0,0,0);document.cookie=a+"="+b+";expires="+d.toGMTString()+";path=/;domain="+c}},k:function(a,
b){return v.get(a,b)}};var c;if(!window.sc_adv_out||!Array.isArray(window.sc_adv_out))window.sc_adv_out=[];if(!window.sc_adv_ids||!Array.isArray(window.sc_adv_ids))window.sc_adv_ids=[];if(typeof window.SC_CId!="undefined"){var e=parseInt(window.SC_CId);if(window.sc_adv_ids.indexOf(e)<0){window.sc_adv_ids.push(e);window.sc_adv_out.push({id:e,domain:window.SC_Domain,settings:window.SC_Set||"",iframe:window.SC_IFrame||0,subid:window.SC_SubId||"",redir:window.SC_redir,add_params:window.SC_add_params,
_sc_params:window._sc_params,_sc_debug:window._sc_debug,ajax:window.SC_Ajax||s})}}if(window.sc_adv_out.length>0)for(;;){e=window.sc_adv_out.pop();if(!e)break;c=new b(e);e.ajax||c.C()}if(c){window.SC_AdvOutBuilder=c;window.SC_AdvOutBuilder.callByAjax=c.B}}).call()}).call();
