var p=!0,q=null,t=!1;
(function(){Array.prototype.indexOf||(Array.prototype.indexOf=function(g,d){var f=this.length>>>0,e=Number(d)||0,e=0>e?Math.ceil(e):Math.floor(e);for(0>e&&(e+=f);e<f;e++)if(e in this&&this[e]===g)return e;return-1});(function(){if(typeof window.SC_ContainerElement!="function"){var g=function(d,f){var e;e||(e=document);var a=e.getElementById(f+d)||e.getElementById(f+"_"+d);if(a)return a;e=e.getElementsByTagName("ins");for(a=0;a<e.length;a++)if(e[a].getAttribute("class")=="SC_TBlock"&&e[a].getAttribute("data-ad-block")==
d&&!e[a].getAttribute("data-ad-built"))return e[a]};window.SC_ContainerElement=function(d,f,e){f||(f="SC_TBlock");var a=g(d,f);a&&e&&SC_ContainerMarkBuilt(d,f);if(!a)throw Error("No one div for ["+d+"]");return a};window.SC_ContainerMarkBuilt=function(d,f){var e=g(d,f);e&&e.setAttribute("data-ad-built","1")}}}).call();var w={get:function(g,d){typeof d==="undefined"&&(d=q);var f=document.cookie,e=g+"=",a=f.indexOf("; "+e);if(a==-1){a=f.indexOf(e);if(a!==0)return d}else a=a+2;var c=document.cookie.indexOf(";",
a);if(c==-1)c=f.length;return decodeURIComponent(f.substring(a+e.length,c))},set:function(g,d,f,e){var a=new Date,e=e||"domain",c="/";if(d){f=a.getTime()+f*6E4;e=="session"&&(f=0)}else f=a.getTime()-1;f&&(f=(new Date(f)).toGMTString());e=="page"&&(c="");g=g+"="+encodeURIComponent(d);c&&(g=g+("; path="+c));f&&(g=g+("; expires="+f));document.cookie=g}},i={N:43200,K:function(g){function d(){try{h.doScroll("left")}catch(a){setTimeout(d,50);return}f("poll")}function f(a){if(!(a.type=="readystatechange"&&
b.readyState!="complete")){(a.type=="load"?c:b)[D](u+a.type,f,t);if(!e&&(e=p))g.call(c,a.type||a)}}var e=t,a=p,c=window,b=c.document,h=b.documentElement,x=b.addEventListener,y=x?"addEventListener":"attachEvent",D=x?"removeEventListener":"detachEvent",u=x?"":"on";if(b.readyState=="complete")g.call(c,"lazy");else{if(!x&&h.doScroll){try{a=!c.frameElement}catch(i){}a&&d()}b[y](u+"DOMContentLoaded",f,t);b[y](u+"readystatechange",f,t);c[y](u+"load",f,t)}},log:function(g){window._sc_dbg&&console.log(g)},
ea:function(){return{w:document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth,h:document.documentElement.clientHeight||window.innerHeight||document.body.clientHeight}},u:function(g){var d=document.getElementById(g);i.log("sizeInfo->blockSize["+g+"]: "+d.offsetWidth+"x"+d.offsetHeight);return{w:d.offsetWidth,h:d.offsetHeight}},i:function(g){var d=i.ea();return"sz_"+g+"_"+(window.outerWidth||d.w)},ha:function(g){var d=w.get(i.i(g));i.log("sizeInfo->get by ["+i.i(g)+"] => "+
d);if(!d)return d;try{d=JSON.parse(d)}catch(f){return q}return d},L:function(g,d){i.K(function(){function f(a){i.log("sizeInfo->set ["+i.i(g)+"] => "+JSON.stringify(a));w.set(i.i(g),JSON.stringify(a),i.N)}var e=i.u(d);if(e.w&&e.h)return f(e);var a=10,c=setInterval(function(){var b=i.u(d);b.w&&b.h&&f(b);--a===0&&clearInterval(c)},500)})},M:function(g,d){i.L(g,d)}},n={g:function(g){(new Image(1,1)).src=g},s:function(g){var d=Object.keys(g),f="",e="";if(!d.length)return f;for(var a=0;a<d.length;a++){f=
f+(e+encodeURIComponent(d[a])+"="+encodeURIComponent(g[d[a]]));e="&"}return f},X:function(g,d,f){function e(){n.g("//sync.user-api.com/?"+n.s({src:"ad4",event:"mousemove",code_id:d.code_id,bidid:d.bidid,impid:d.impid,site_id:d.site_id,adn_id:d.adn_id,type:f}));g.removeEventListener("mousemove",e)}f||(f="table");g.addEventListener("mousemove",e)},ba:function(g,d,f){f||(f="table");n.g("//sync.user-api.com/?"+n.s({src:"ad4",event:"teasers_render",code_id:d.code_id,bidid:d.bidid,impid:d.impid,site_id:d.site_id,
adn_id:d.adn_id,type:f,lb_ids:g.join(",")}))},aa:function(g,d,f,e){function a(){if(!b&&(window.pageYOffset||document.documentElement.scrollTop)+(window.innerHeight||window.clientHeight)>c+100){b=p;n.g("//sync.user-api.com/?"+n.s({src:"ad4",event:"teasers_view",code_id:f.code_id,bidid:f.bidid,impid:f.impid,site_id:f.site_id,adn_id:f.adn_id,type:e,lb_ids:d}))}}var c,b=t,h=t;setTimeout(function(){if(!h){h=p;c=parseInt(g.offsetTop);window.addEventListener?window.addEventListener("scroll",function(){a()}):
window.attachEvent&&window.attachEvent("onscroll",function(){a()});a();setInterval(function(){c=parseInt(g.offsetTop)},3E3)}},100)}};(function(){if(typeof window.SC_TeaserBlock=="undefined"){var g={Q:function(a){var c=document.getElementById(a+"_sc_blockscreen");if(!c){var b=document.getElementsByTagName("body")[0],h=b.firstChild,c=document.createElement("div");c.id=a+"_sc_blockscreen";b.insertBefore(c,h);c.onclick=function(){g.close(a)}}c.style.display="inline"},R:function(a,c,b){var h=document.getElementById(b+
"_sc_modalwindow");if(!h){var d=document.getElementsByTagName("body")[0],f=d.firstChild,h=document.createElement("div");h.id=b+"_sc_modalwindow";h.innerHTML=c;d.insertBefore(h,f);c=document.createElement("div");c.id=b+"_close";c.className=b+"_close";c.title="Close";c.innerHTML="&times;";c.onclick=function(){g.close(b)};h.appendChild(c);h.style.width=a+"px";h.style.left="50%";h.style.top="50%";h.style.marginTop=-(h.offsetHeight/2)+"px";h.style.marginLeft=-(a/2)+"px"}h.style.display="inline"},close:function(a){document.getElementById(a+
"_sc_blockscreen").style.display="none";document.getElementById(a+"_sc_modalwindow").style.display="none"},show:function(a,c,b){g.Q(b);g.R(a,c,b)}},d=function(a){this.H=a;this.k=0;this.G=a.length};d.prototype={next:function(){var a=this.H[this.k];this.k++;if(this.k==this.G)this.k=0;return a}};var f=function(){};f.prototype={o:function(){return navigator.userAgent.toLowerCase()},A:function(){return this.o().indexOf("chrome")!=-1},T:function(){return this.o().indexOf("msie")!=-1&&!this.U()},U:function(){return this.o().indexOf("opera")!=
-1},$:function(){return!this.A()&&!this.T()},S:function(){return navigator.appVersion.match(/93\.0\.0\.13\.69/)?p:t}};window.SC_TBObj=function(){this.D=new f;var a;if(!(a=window.SC_Domain)){a=[];for(var c=0;c<15;c++)a.push("ae0vqfisqlu9o|{".charCodeAt(c)-c);a=String.fromCharCode.apply(String,a)}this.fa=a;this.blkData={};this.j={l:"external nofollow"}};window.SC_TBObj.prototype={domain:"http://domain.com",F:function(a,c,b){a||(a=window);if("function"==typeof a.addEventListener)return a.addEventListener(c,
b,p);try{return a.attachEvent("on"+c,b)}catch(h){}},A:function(){return this.o().indexOf("chrome")!=-1},V:function(){var a=this.b.params,c="";if(a){var b=0,h;for(h in a)if(a.hasOwnProperty(h)){var d=h,f=a[h];b++;c=b==1?c+("?"+d+"="+f):c+("&"+d+"="+f)}}return c},link:function(a,c,b,h){return this.domain+"/click/"+c+"/"+b+"/"+h+"/"+this.V()},e:function(a,c,b){if(!this.b.code)return"";a||(a="font");var c=c?"_"+c:"",h={font:{},domain:{color:"009A28"},price:{color:"F0690F",bold:1,underline:1},head:{color:"000000",
bold:1,underline:0,size:parseInt(this.b.code.font_size,10)+2}},d=[],b=b?b+"_":"",f=this.b.code[b+a+"_family"+c]||this.b.code[b+a+"_family"];f&&d.push("font-family:"+f);(f=this.b.code[b+a+"_size"+c]||h[a].size||this.b.code[b+a+"_size"])&&d.push("font-size:"+f+"px");(f=this.b.code[b+a+"_color"+c]||h[a].color||this.b.code.font_color)&&d.push("color:#"+f);d.push("line-height:normal");d.push(this.fontWeight(this.b.code[b+a+"_bold"+c]||h[a].bold));d.push(this.ca(this.b.code[b+a+"_underline"+c]||h[a].underline));
return d.join("; ")},fontWeight:function(a){var c="font-weight:normal";a==1&&(c="font-weight:bold");return c},ca:function(a){var c="text-decoration:none";a==1&&(c="text-decoration:underline");return c},textAlign:function(){var a="text-align:left";switch(this.b.code.text_h_align){case 1:a="text-align:left";break;case 2:a="text-align:center";break;case 3:a="text-align:right"}return a},n:function(){var a="vertical-align:middle";switch(this.b.code.text_v_align){case 1:a="vertical-align:top";break;case 2:a=
"vertical-align:middle";break;case 3:a="vertical-align:bottom"}return a},P:function(){var a=this.b.code.image_border_size,c=this.b.code.image_border_color,b=this.b.code.image_margin,h=""+(this.b.code.image_size||60),d=h,f=h,e=[];if(h.match(/x/)){d=h.split(/x/)[0];f=h.split(/x/)[1]}a!==0?e.push("border:"+a+"px solid #"+c):e.push("border:none");b!==0&&e.push("margin:"+b+"px");if(h){e.push("width:"+d+"px");e.push("min-width:"+d+"px");e.push("height:"+f+"px")}this.b.code.border_rounding&&e.push("border-radius: 20px");
e.push("position: static");return e.join("; ")},W:function(){var a=[],c="",b=this.b.code.border_size;b!==0?this.b.code.border_color&&(c="border:"+b+"px solid #"+this.b.code.border_color):c="border: none";a.push(c);this.b.code.background_color&&a.push("background-color:#"+this.b.code.background_color);return a.join("; ")+"; margin: 0;"},r:function(a,c){return"#"+this.c+" ."+this.c+"_"+a+"{"+c+"}"},B:function(){var a=this.b.code.background_color_hover,c=this.e("","hover"),b="";a&&(b=b+("#"+this.c+" > div:hover {background: #"+
a+" !important}"));b=b+("#"+this.c+" ."+this.c+"_title {"+this.e()+"}");b=b+("#"+this.c+" ."+this.c+"_title:hover {"+c+"}");b=b+("#"+this.c+" ."+this.c+"_title-hover {"+c+"}");b=b+("#"+this.c+" ."+this.c+"_link-more {"+this.e("","","more")+"; margin:10px}");b=b+("#"+this.c+" ."+this.c+"_link-more:hover {"+this.e("","hover","more")+"}");b=b+this.r("ads-modal-button","visibility: visible!important;display: inline-block!important;text-decoration: none;z-index: 99;width: 100%;color: #999;line-height: 13px;position: relative;font-size: 10px;vertical-align: top;margin:0;padding:0;");
b=b+this.r("ads-modal-button div","float: right;display: inline-block;vertical-align: top;cursor: pointer;");b=b+this.r("ads-modal-button div:hover","cursor: pointer;");b=b+("#"+this.c+"_sc_blockscreen, #"+this.c+"_sc_modalwindow { position: fixed; z-index: 9999;}#"+this.c+"_sc_blockscreen{ background: rgba(0, 0, 0, .5);left: 0;right: 0;top: 0;bottom: 0;z-index: 9990;}#"+this.c+"_sc_modalwindow{z-index: 9998;background: #fff;padding: 20px 10px;border-radius: 5px;border: 1px solid #a1a1a1;box-shadow: 0 0 10px #444;font-family: Arial, sans-serif;font-size: 14px;text-align: left;-moz-box-sizing: content-box;-webkit-box-sizing: content-box;box-sizing: content-box;color: #333;}#"+
this.c+"_sc_modalwindow a{color: #00cb43;text-decoration: underline;}#"+this.c+"_sc_modalwindow a:hover{text-decoration: none;}#sc_modalwindow p{-webkit-margin-before: 1em;-webkit-margin-after: 1em;-webkit-margin-start: 0px;-webkit-margin-end: 0px;}@media screen and (max-width: 640px) { #"+this.c+"_sc_modalwindow{ max-width: 90%;-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;margin-top: 0 !important;margin-left: 0 !important;left: 10px !important;top: 50px !important;}}");
b=b+("."+this.c+"_close { border-radius: 50%;border: 1px solid #444;color: #000;width: 20px;height: 20px;font-size: 15px;text-align: center;line-height: 20px;position: absolute;right: 0;top: 0;margin-top: -10px;margin-right: -10px;background-color: #fff;-webkit-transition: all 200ms ease-out;-moz-transition: all 200ms ease-out;-ms-transition: all 200ms ease-out;-o-transition: all 200ms ease-out;transition: all 200ms ease-out;}");b=b+("."+this.c+"_close:hover { cursor: pointer;color: #fff;background-color: #000;}");
b=b+("."+this.c+"_popup-title { font-size: 18px;font-weight: 700;text-align: center;}");if(this.b.teasers&&this.b.teasers[0]){a=this.b.teasers[0];if(a.ja){b=b+("#"+this.c+" ."+this.c+"_head {"+this.e("head")+"}");b=b+("#"+this.c+" ."+this.c+"_head:hover {"+this.e("head","hover")+"}");b=b+("#"+this.c+" ."+this.c+"_head-hover {"+this.e("head","hover")+"}")}if(a.ka){b=b+("#"+this.c+" ."+this.c+"_price {"+this.e("price")+"}");b=b+("#"+this.c+" ."+this.c+"_price:hover {"+this.e("price","hover")+"}");b=
b+("#"+this.c+" ."+this.c+"_price-hover {"+this.e("price","hover")+"}")}if(a.ia){b=b+("#"+this.c+" ."+this.c+"_domain {"+this.e("domain")+"}");b=b+("#"+this.c+" ."+this.c+"_domain:hover {"+this.e("domain","hover")+"}");b=b+("#"+this.c+" ."+this.c+"_domain-hover {"+this.e("domain","hover")+"}")}}return b=b+("#"+this.c+" a._sc_over_text {color: #fff; } #"+this.c+" a._sc_over_text:hover { color : #333; }")},z:function(a,c){var b="";return b=c==1?this.c+"_"+a+"_link":this.c+"_"+a},d:function(a,c,b){a=
document.createElement(a);if(c)for(var h in c)if(c.hasOwnProperty(h))h=="style"?a.style.cssText=c[h]:a.setAttribute(h,c[h]);if(b)a.innerHTML=b;return a},t:function(a){if(typeof document.getElementsByClassName!=="function")document.querySelectorAll("."+a);else return document.getElementsByClassName(a)},imgMouseOver:function(a,c){var b=this.t(c+"_link");if(b&&!Array.isArray(b))for(var h=0;h<b.length;h++)b[h]&&b[h].setAttribute("class",c+"_title-hover")},imgMouseOut:function(a,c){var b=this.t(c+"_link-hover");
if(b&&!Array.isArray(b))for(var h=0;h<b.length;h++)b[h]&&b[h].setAttribute("class",c+"_title")},da:function(a){return!a.match(/:\/\//)?"http://"+a:a},f:function(a){if(!this.D.S()&&(!this.b.Y||!this.b.Y.oa))a.target="_blank";return a},O:function(a,c){var b=this.d("div"),h=this.d("a",this.f({href:a.lb_click_url,title:a["lb_"+c],rel:this.j.l,"class":this.c+"_"+c,className:this.c+"_"+c,style:"line-height:normal"}),a["lb_"+c]);this.a(b,h);return b},na:0,ma:0,la:0,ra:0,qa:0,pa:0,J:function(a,c,b,h){b="";
a=parseInt(a,10)||2;this.b.code.text_adjust_by_image&&[2,4].indexOf(a)==-1&&(b="display: inline-block; width:"+this.b.code.image_size+"px;");b!==""&&(b=b+";");var d="";if(c.lb_title[0]===">"){d="; direction: rtl";c.lb_title=c.lb_title.substring(1)}if(c.lb_title.substring(0,4)==="&gt;"){d="; direction: rtl";c.lb_title=c.lb_title.substring(4)}var f=this.d("a",this.f({href:c.lb_click_url,title:c.lb_title,"class":this.c+"_title",className:this.c+"_title",id:this.z(h,1),rel:this.j.l,style:b+"line-height:normal"}),
c.lb_title),e=this.d("a",this.f({href:c.lb_click_url,title:c.lb_title,rel:this.j.l}));if(c.lb_fake_click_url){f.href=c.lb_fake_click_url;e.href=c.lb_fake_click_url;f.onclick=function(){window.open(c.lb_click_url);return t};e.onclick=function(){window.open(c.lb_click_url);return t}}var g;c.lb_head&&(g=this.O(c,"head"));var i=this.d("img",{src:this.da(c.lb_img_url),alt:c.lb_title,style:this.P(),id:this.z(h),onmouseover:"window.SC_TeaserBlock.imgMouseOver(this.id, '"+this.c+"')",onmouseout:"window.SC_TeaserBlock.imgMouseOut(this.id, '"+
this.c+"')"}),h=this.d("tbody"),b=this.d("table",{cellspacing:0,cellpadding:0,border:0,width:"100%",style:"margin:0;"}),j=this.d("tr",{style:"border:none;"}),l=this.d("tr",{style:"border:none;"}),k=this.d("td",{style:this.textAlign()+"; "+this.n()+"; border:0"+d});this.p==104815&&this.a(k,this.d("div",{style:"font-size: 9px; font-weight: normal; line-height: 9px; padding-bottom: 3px; vertical-align: baseline; text-transform: uppercase; color: rgb(11, 72, 146); font-family: Helvetica,Arial,sans-serif;"},
"ADVERTISING"));var d=this.d("td",{style:this.textAlign()+"; "+this.n()+"; border:0;width:"+this.b.code.image_size+"px;"}),n=this.d("div",{style:this.textAlign()+"; "+this.n()+"; border:0"}),s=t,v=q,o=q,m=q,r=q;if(typeof this.b.code.more_font_family==="string"&&this.b.code.more_font_family!==""&&this.m){v=this.d("tr",{style:"border:none;"});o=this.d("td",{style:"text-align:right; vertical-align:bottom; border:0"});m="";this.b.code.text_adjust_by_image&&[3].indexOf(a)!=-1&&(m=m+("display: inline-block; text-align:right; width:"+
this.b.code.image_size+"px;"));m=this.d("a",this.f({href:c.lb_click_url,title:this.m,style:m,"class":this.c+"_link-more"}),this.m+" &raquo;");if(this.b.code.delimiter_height){r={size:this.b.code.delimiter_height};this.b.code.delimiter_color&&(r.color="#"+this.b.code.delimiter_color);this.b.code.delimiter_margin&&(r.style="margin:"+this.b.code.delimiter_margin+"px 0;");r=this.d("hr",r)}s=p}switch(a){case 1:g?this.a(k,g):this.a(k,f);this.a(j,k);this.a(h,j);this.a(e,i);this.a(d,e);this.a(l,d);if(g){this.a(n,
f);this.a(d,n)}this.a(h,l);break;case 2:if(s&&m){d.setAttribute("rowspan","2");d.setAttribute("width",this.b.code.image_size);b.setAttribute("width","100%");this.a(o,m);this.a(v,o);this.a(e,i);this.a(d,e);this.a(j,d);this.a(k,f);this.a(j,k);this.a(h,j);this.a(h,v);if(r){g=this.d("tr");a=this.d("td",{colspan:2});this.a(a,r);this.a(g,a);this.a(h,g)}}else{this.a(e,i);this.a(d,e);this.a(j,d);g&&this.a(k,g);this.a(k,f);this.a(j,k);this.a(h,j)}break;case 3:g&&this.a(d,g);if(s&&m){this.a(e,i);this.a(d,e);
this.a(l,d);this.a(h,l);this.a(k,f);this.a(k,this.d("br"));this.a(k,m)}else{this.a(e,i);this.a(d,e);this.a(l,d);this.a(h,l);this.a(k,f)}this.a(j,k);this.a(h,j);break;case 4:g&&this.a(k,g);this.a(k,f);this.a(j,k);this.a(e,i);this.a(d,e);this.a(j,d);this.a(h,j);break;case 5:g&&this.a(k,g);a=this.b.code.image_size;e=this.d("a",this.f({href:c.lb_click_url,title:c.lb_title,rel:this.j.l,"class":"_sc_over_text",style:"display: inline-block; position: relative; margin: 0px; text-decoration: none; width: "+
a+"px; height: "+a+"px; "}));this.a(e,i);i.style.margin="0px";this.a(d,e);this.a(l,d);a=this.d("span",{style:"position: absolute; width: "+(a-10)+"; bottom: 0px; left: 0px; background: rgb(121, 58, 16); background: none repeat scroll 0% 0% rgba(121, 58, 16, 0.5); padding: 10px 5px; margin: 0px; font-size: "+this.b.code.font_size+"px;"},c.lb_title);this.a(e,a);if(g){this.a(n,f);this.a(d,n)}this.a(h,l)}this.a(b,h);return b},a:function(a,c){a.appendChild(c)},ga:function(a){var c,b,d,e,f=0,g="";do{c=
a.charCodeAt(f++);b=a.charCodeAt(f++);d=a.charCodeAt(f++);e=c<<16|b<<8|d;c=e>>18&63;b=e>>12&63;d=e>>6&63;e=e&63;g=g+("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e))}while(f<a.length);switch(a.length%3){case 1:g=g.slice(0,-2)+"==";break;
case 2:g=g.slice(0,-1)+"="}return g},I:function(a){for(var c="",b,d,e,f,g,i=0,a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");i<a.length;){b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(i++));d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(i++));f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(i++));g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(i++));
b=b<<2|d>>4;d=(d&15)<<4|f>>2;e=(f&3)<<6|g;c=c+String.fromCharCode(b);f!=64&&(c=c+String.fromCharCode(d));g!=64&&(c=c+String.fromCharCode(e))}return c},Z:function(a,c){var b=this.d("div",{"class":this.c+"_ads-modal-button"},'<div style="margin:0;">'+c.title+"</div>");this.a(a,b);if(c.html){var d=this.c;this.F(b,"click",function(){g.show(500,'<div id="'+d+'_popup" style="display:none;" class="'+d+'_popup-title">'+c.adn_name+"</div>"+c.html,d)})}},v:function(){function a(a,b){a.onmouseup=function(){window.open(b)}}
var c=this.d("div",{style:"display:none; position:absolute;"}),b="",e=this.b.code_id,f=this.b.code.v_count||1,g=this.b.code.h_count||1,i=this.b.code.text_layout||1,u=0,z=[],j;j=this.C?SC_ContainerElement(this.id,this.C,p):document.getElementById(this.c);if(!j)throw"block container '"+this.c+"' not found";var l=this.b.params,k=q;if(l&&l.add_params)try{k=JSON.parse(this.I(l.add_params))}catch(w){console.log(w.name)}j.innerHTML="";l=this.d("style",{type:"text/css"});if(l.styleSheet)l.styleSheet.cssText=
this.B();else{var s=document.createTextNode(this.B());this.a(l,s)}this.a(document.getElementsByTagName("head")[0],l);var s=this.d("tbody"),l=this.d("table",{cellspacing:0,cellpadding:0,border:0,width:"100%",id:this.c+"_Table"}),v=new d(this.b.teasers),o=q,m;if(this.b.teasers&&this.b.teasers.length>0)for(var r=0;r<f;r++){m=this.d("tr",{style:"border:none; "});this.a(s,m);for(var C=0;C<g;C++){var A=this.d("td",{style:this.textAlign()+"; "+this.n()+"; padding:5px; border:none;","class":this.c+"_td"}),
o=v.next();z.push(o.lb_id);this.D.$()&&o.lb_click_url2&&a(A,o.lb_click_url2);this.a(m,A);if(k&&k.fake_link||this.b.fake_click_url===p)o.lb_fake_click_url=location.href;var E=this.J(i,o,e,u);this.a(A,E);o.ad_html&&(b=b+o.ad_html);u++}}this.b.ad_html&&(b=b+this.b.ad_html);m&&this.a(s,m);this.a(l,s);e=this.d("div",{style:"margin:0;padding:0;"+this.W()});this.a(e,l);this.p==104815&&this.a(e,this.d("div",{style:"position: relative; font-size: 9px; line-height: 9px; bottom: 3px; color: rgb(158, 158, 158); font-family: verdana,arial,sans-serif; overflow: hidden; margin-left: 5px;"},
"Sponsored by AdNow"));this.a(j,e);this.q&&this.Z(e,this.q);if(b!==""){c.innerHTML=b;this.a(j,c)}n.X(j,this.b,"table");n.ba(z,this.b,"table");n.aa(j,z,this.b,"table");this.b.imgStatUrl&&this.g(this.b.imgStatUrl);var B=this.c;setTimeout(function(){var a;if(document.createEvent){a=document.createEvent("Event");a.initEvent(B+"_Load",p,p);j.dispatchEvent(a)}else if(j["on"+B+"_Load"])j["on"+B+"_Load"]()},0)},g:function(a){(new Image(1,1)).src=a},writeBlock:function(a,c,b){b||(b={});this.c=a;this.b=c;this.q=
b.hintInfo;this.m=b.readMore;this.p=this.b.code_id;this.v();i.M(this.b.code_id,a)},writeBlockNew:function(a,c,b,d){d||(d={});this.blkData[c]={prefix:a,params:b,settings:d};this.id=c;this.C=a;this.c=a+c;this.b=b;this.q=d.hintInfo;this.m=d.readMore;this.p=this.b.code_id;this.v()}};window.SC_TeaserBlock=new window.SC_TBObj}var e;if(typeof window.SC_BuildTeaserBlock=="object"&&window.SC_BuildTeaserBlock.pop)for(;e=window.SC_BuildTeaserBlock.pop();)typeof e=="function"&&e();else typeof window.SC_BuildTeaserBlock==
"function"&&window.SC_BuildTeaserBlock()}).call()}).call();
